### PR TITLE
Correct response for payu bot

### PR DESCRIPTION
**Pull request by jroszkiewicz**
Default response from payum bundle is invalid (204 http status code), so we need to force 200 http status code with "OK" message.

### CODE REVIEW

**Comment by jroszkiewicz** [comment]
Proof: http://developers.payu.com/pl/restapi.html#notifications

**Comment by mkurzeja** [comment]
I know the repo is not formatted according to php-cs-fixer (and in general psr-1, psr-2 rules) but could you please fix the new lines to use 4 spaces as indentation?

Thanks for your commits, I'll be happy to merge them after the formatting is fixed.

**Comment by jroszkiewicz** [comment]
@mkurzeja fixed ;-)

**Comment by mkurzeja** [comment]
Thank you @jroszkiewicz !

**Pull request merged**
